### ISSUE TITLE
pdftotext binary not installed

### ISSUE THREAD

**Issue by papascott** [josh/pdftotext#5]
Building the Dockerfile does not install the `pdftotext` binary, since it is not included in the xpdf package for Alpine Linux.

```
[Tue Sep 24 07:32:33.376081 2019] [cgi:error] [pid 7] [client 172.17.0.1:57228] AH01215: /usr/local/apache2/cgi-bin/pdftotext: line 69: pdftotext: command not found: /usr/local/apache2/cgi-bin/pdftotext
172.17.0.1 - - [24/Sep/2019:07:32:33 +0000] "PUT /cgi-bin/pdftotext HTTP/1.1" 200 -
```

I changed `apk add xpdf` to `apk add poppler-utils` in the Dockerfile to install the poppler version of pdftotext.

**Comment by josh** [comment]
You're right! I wonder if this was working at some point.

Though it's suspicious that the tests don't fail even if the command is missing. Maybe we can add a `which pdftotext` to the top of `cgi-bin/pdftotext` and 500 if it's missing.

Do you want to open a Pull Request for the `poppler-utils` change? It seemed to work for me as well.

**Comment by papascott** [comment]
OK, done! 😃 Another thing to consider is that the poppler `texttopdf` has slightly different options than xpdf `texttopdf`, so we might want to adjust the flags section of `cgi-bin/pdftotext` accordingly.
